SELECT CONFLICTS.ID, REFERENCE.RELATIVEID, REFERENCE."VALUE", ACTUAL."VALUE" 
FROM CONFLICTS
JOIN ACTUAL ON ACTUAL.ID = CONFLICTS.ACTUALID 
JOIN REFERENCE ON REFERENCE.ID = CONFLICTS.REFERENCEID 
WHERE CONFLICTTYPE <> 0