/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.opencompare.ui;

import javax.swing.JOptionPane;

/**
 *
 * @author ckulak
 */
public class FilterDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = 1L;

    private boolean userConfirmed = false;
    
    private final boolean originalDisplayIdentical;
    
    /**
     * Creates new form FilterDialog
     */
    public FilterDialog(java.awt.Frame parent, boolean modal, boolean originalDisplayIdentical) {
        super(parent, modal);
        initComponents();
        
        this.originalDisplayIdentical = originalDisplayIdentical;
        checkboxDisplayIdentical.setSelected(originalDisplayIdentical);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonOk = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        checkboxDisplayIdentical = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Filter");

        buttonOk.setText("OK");
        buttonOk.setToolTipText("");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        checkboxDisplayIdentical.setText("Display identical items");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(buttonCancel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(buttonOk))
                    .add(layout.createSequentialGroup()
                        .add(checkboxDisplayIdentical)
                        .add(0, 74, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(checkboxDisplayIdentical)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 81, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(buttonOk)
                    .add(buttonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        if (originalDisplayIdentical != isDisplayIdentical()) {
            // Something has changed
            if (JOptionPane.showConfirmDialog(this, "Are you sure you want to change the filter? The snapshot will be reloaded.", "Confirmation", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                userConfirmed = true;
                setVisible(false);
            }
        } else {
            buttonCancelActionPerformed(evt);
        }
    }//GEN-LAST:event_buttonOkActionPerformed

    public boolean isUserConfirmed() {
        return userConfirmed;
    }
    
    public boolean isDisplayIdentical() {
        return checkboxDisplayIdentical.isSelected();
    }
    
    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        userConfirmed = false;
        setVisible(false);
    }//GEN-LAST:event_buttonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonOk;
    private javax.swing.JCheckBox checkboxDisplayIdentical;
    // End of variables declaration//GEN-END:variables
}
